### ISSUE TITLE
Unable to reproduce the output on with cuda 10.4 on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by ravirathee** [KAdamek/AAFFT#1]
This is the output when I type in "make" command

Output : 

rm -f *.o *.~ FFT.exe
g++ -c FFT.c -O3 -Wall -Wextra -I/usr/local/cuda-11/include
/usr/local/cuda-11/bin/nvcc -c FFT-GPU-32bit.cu -O3 -arch=sm_70 --ptxas-options=-v --use_fast_math -Xcompiler -Wextra -lineinfo
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI26FFT_4096_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI26FFT_4096_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 33792 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI16FFT_4096_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI16FFT_4096_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 33792 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI26FFT_4096_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI26FFT_4096_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 33792 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI16FFT_4096_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI16FFT_4096_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 33792 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI26FFT_2048_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI26FFT_2048_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 16896 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI16FFT_2048_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI16FFT_2048_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 16896 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI26FFT_2048_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI26FFT_2048_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 16896 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI16FFT_2048_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI16FFT_2048_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 16896 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI26FFT_1024_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI26FFT_1024_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 8448 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI16FFT_1024_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI16FFT_1024_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 8448 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI26FFT_1024_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI26FFT_1024_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 8448 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI16FFT_1024_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI16FFT_1024_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 8448 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI25FFT_512_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI25FFT_512_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 4224 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI15FFT_512_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI15FFT_512_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 4224 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI25FFT_512_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI25FFT_512_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 4224 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI15FFT_512_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI15FFT_512_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 4224 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI25FFT_256_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI25FFT_256_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 2112 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI15FFT_256_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI15FFT_256_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 2112 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI25FFT_256_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI25FFT_256_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 2112 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI15FFT_256_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI15FFT_256_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 2112 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI25FFT_128_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI25FFT_128_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI15FFT_128_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI15FFT_128_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI25FFT_128_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI25FFT_128_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI15FFT_128_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI15FFT_128_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI24FFT_64_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI24FFT_64_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI14FFT_64_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI14FFT_64_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI24FFT_64_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI24FFT_64_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI14FFT_64_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI14FFT_64_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI24FFT_32_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI24FFT_32_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1024 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI14FFT_32_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI14FFT_32_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1024 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI24FFT_32_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI24FFT_32_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1024 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_multipleI14FFT_32_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_multipleI14FFT_32_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1024 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI26FFT_4096_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI26FFT_4096_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 33792 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI16FFT_4096_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI16FFT_4096_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 33792 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI26FFT_4096_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI26FFT_4096_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 33792 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI16FFT_4096_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI16FFT_4096_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 33792 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI26FFT_2048_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI26FFT_2048_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 16896 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI16FFT_2048_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI16FFT_2048_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 16896 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI26FFT_2048_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI26FFT_2048_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 16896 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI16FFT_2048_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI16FFT_2048_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 16896 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI26FFT_1024_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI26FFT_1024_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 8448 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI16FFT_1024_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI16FFT_1024_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 8448 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI26FFT_1024_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI26FFT_1024_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 8448 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI16FFT_1024_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI16FFT_1024_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 8448 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI25FFT_512_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI25FFT_512_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 4224 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI15FFT_512_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI15FFT_512_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 4224 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI25FFT_512_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI25FFT_512_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 4224 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI15FFT_512_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI15FFT_512_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 4224 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI25FFT_256_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI25FFT_256_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 2112 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI15FFT_256_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI15FFT_256_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 2112 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI25FFT_256_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI25FFT_256_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 2112 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI15FFT_256_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI15FFT_256_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 2112 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI25FFT_128_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI25FFT_128_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI15FFT_128_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI15FFT_128_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 31 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI25FFT_128_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI25FFT_128_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI15FFT_128_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI15FFT_128_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 31 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI24FFT_64_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI24FFT_64_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 31 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI14FFT_64_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI14FFT_64_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI24FFT_64_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI24FFT_64_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 31 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI14FFT_64_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI14FFT_64_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1056 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI24FFT_32_inverse_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI24FFT_32_inverse_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1024 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI14FFT_32_inverseEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI14FFT_32_inverseEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1024 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI24FFT_32_forward_noreorderEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI24FFT_32_forward_noreorderEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1024 bytes smem, 368 bytes cmem[0]
ptxas info    : Compiling entry function '_Z18SMFFT_DIT_externalI14FFT_32_forwardEvP6float2S2_' for 'sm_70'
ptxas info    : Function properties for _Z18SMFFT_DIT_externalI14FFT_32_forwardEvP6float2S2_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 1024 bytes smem, 368 bytes cmem[0]
/usr/local/cuda-11/bin/nvcc -o FFT.exe FFT-GPU-32bit.o FFT.o -L/usr/local/cuda-11/lib64 -lcudart -lcufft -lcuda -O3 -arch=sm_70 --ptxas-options=-v --use_fast_math -Xcompiler -Wextra -lineinfo

**Comment by ravirathee** [comment]
and this is the output when I try to use " ./FFT.exe "

Argument error!
 1) FFT length
 2) number of FFTs
 3) the number of kernel executions
 4) do inverse FFT 1=yes 0=no
 5) reorder elements to correct order 1=yes 0=no
For example: FFT.exe 1024 100000 20 0 1


So, when I use the given example : "  ./FFT.exe 1024 100000 20 0 1  "

It gives the following error:

Host memory allocation...	done.
Host memory memset...		done.
Initializing data with random numbers...	done.

  Device has 4038.750 MB of total memory, which 3673.875 MB is available.
  Running cuFFT...: 		done in 16.8673 ms.
  FFT size: 1024; cuFFT time = 16.867 ms;

  Device has 4038.750 MB of total memory, which 3665.875 MB is available.
  Running shared memory FFT (Cooley-Tukey) 100 times per GPU kernel (eliminates device memory)... done in 0.0013584 ms.
CUDA error at: FFT-GPU-32bit.cu:876
no kernel image is available for execution on the device cudaGetLastError()

**Comment by KAdamek** [comment]
This is most probably by compiling the code with wrong architecture. Check which major and minor compute capability you GPU has.
